name: Deploy on push
on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: webserver-vista
    defaults:
      run:
        shell: powershell
    steps:
      - name: Pull to IIS folder
        run: |
          $path = 'C:\_www\bal_010_cz_vista_resp\App_Firma'
          git config --global --add safe.directory $path
          git -C $path fetch --prune
          git -C $path reset --hard origin/main